# Generated by Django 3.0.5 on 2020-05-08 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='uploads/banners')),
                ('banner_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_message', models.TextField()),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField()),
                ('about_image', models.ImageField(upload_to='uploads/about')),
                ('footer_text', models.CharField(max_length=254)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('call_time', models.CharField(max_length=100)),
                ('resident_address', models.CharField(max_length=254)),
                ('postal_code', models.CharField(max_length=50)),
                ('facebook_link', models.URLField(max_length=254)),
                ('twitter_link', models.URLField(max_length=254)),
                ('youtube_link', models.URLField(max_length=254)),
                ('instagram_link', models.URLField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(upload_to='uploads/logos')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=50)),
                ('song_file', models.FileField(upload_to='uploads/songs')),
                ('song_upload_date', models.DateTimeField(auto_now=True)),
                ('song_image', models.ImageField(upload_to='uploads/songs')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=50)),
                ('video_event_name', models.CharField(max_length=100)),
                ('video_link', models.URLField(max_length=254)),
                ('video_image', models.ImageField(upload_to='uploads/videos')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuv_app.Video')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuv_app.Song')),
            ],
        ),
    ]
