# Generated by Django 3.0.5 on 2020-05-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='image_description',
            field=models.CharField(default='Image description', max_length=50),
            preserve_default=False,
        ),
    ]
