# Generated by Django 3.0.5 on 2020-05-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuv_app', '0004_auto_20200510_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetter',
        ),
    ]
