# Generated by Django 3.0.5 on 2020-05-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuv_app', '0007_song_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_file',
        ),
        migrations.AddField(
            model_name='song',
            name='song_link',
            field=models.URLField(default='www.song.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='song_lyrics',
            field=models.TextField(default='The lyrics'),
            preserve_default=False,
        ),
    ]
